version: '3.4'

services:
  moonstone.server:
    image: ${DOCKER_REGISTRY-}moonstoneserver
    build:
      context: .
      dockerfile: src/Moonstone.Server/Dockerfile
    ports:
      - 9111:9111
    environment:
      MOONSTONE_PATH: /opt/moonstone/
    volumes:
      - ./bin/config/config.yml:/opt/moonstone/config/config.yml:ro

  moonstone.mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: moonstone
      MYSQL_USER: moonstone_usr
      MYSQL_PASSWORD: moonstone_pwd
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3308:3306"
    expose:
      - "3308"
    volumes:
      - ./bin/_docker/mysql:/var/lib/mysql
